### ISSUE TITLE
No requirements file on django server

### ISSUE THREAD

**Issue by Axel-Girard** [agathe-rc/gmao-app#1]
Bonjour,

Je n'ai pas réussi à installer ton serveur python, il me manque la version de python que tu utilises ainsi qu'un fichier de prérequis pour les module pip. J'ai l'habitude d'utiliser pyenv afin de créer différents environnements pour mes projets python, ça me permet de n'avoir d'installer que les modules nécessaires et sur la version de python que je souhaite. Te serait-il possible de me fournir un tel fichier et de me dire la version de python que tu utilises ?
Un simple `pip freeze` fera l'affaire.

PS: Tu peux ignorer le dossier node_modules dans git, ça rendra le projet plus petit, mais c'est un détail.

**Comment by agathe-rc** [comment]
Bonjour Axel,

La version de python que j'utilise : Python 2.7.12
J'ai ajouté un fichier requirements.txt qui comprend un pip freeze sur ma machine en local, mais les modules que j'utilise pour cette app sont uniquement :
Django==1.11.6
django-cors-headers==3.0.2
djangorestframework==3.9.4

**Comment by Axel-Girard** [comment]
Merci,

J'utilise python 2.7.16 (parce qu'il était déjà installé sur mon poste) et j'ai l'erreur suivante, après avoir installer les requirements :
```
url(r'^api/', include(router.urls, namespace='api'))
  File "/home/axel/.pyenv/versions/agathe/lib/python3.7/site-packages/django/urls/conf.py", line 39, in include
    'Specifying a namespace in include() without providing an app_name '
django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
```

J'ai regardé rapidement, il semble que le problème vienne de cette ligne `url(r'^api/', include(router.urls, namespace='api'))` dans le fichier urls.py qui devrait ressembler à ça `url(r'^api/', include((router.urls, 'api'), namespace='api'))`

Tu arrives bien à lancer ton serveur avec ton code ? C'est peut être la version mineur qui change ça, juste pour savoir.

**Comment by agathe-rc** [comment]
Oui de mon côté le serveur se lance sans problème.
J'ai modifié la syntaxe du include(), dis-moi si cela fonctionne.

**Comment by Axel-Girard** [comment]
Merci beaucoup, c'est parfait !

**Comment by Axel-Girard** [comment]
Si jamais ça peut te détendre, j'ai fini la relecture de code (on en parlera demain) et je trouve ça très bien. Ton code est propre, lisible et fonctionne bien. Il répond à toutes les exigences du test et il y a même des références à Nautilux donc c'est super !
![Alt text](https://i.pinimg.com/originals/00/56/3e/00563e7eafa2022566cab936da62c427.gif)

**Comment by agathe-rc** [comment]
Merci beaucoup pour ton retour, effectivement je suis plus détendue... :)

Le mer. 25 sept. 2019 à 15:15, Axel-Girard <notifications@github.com> a
écrit :
